### PR TITLE
Make cronfile work because of filename error

### PR DESCRIPTION
**Pull request by raneq**
cron prohibits dots in the cron.d filenames. Therefore, we need to escape or replace them. I chose to replace dots with underscores

### CODE REVIEW

**Review by enricostano — COMMENTED** [review]
If it's cronfile complaining, why don't we do the `s/./_` directly there instead of touching more generic variables?

**Comment by raneq** [comment]
> If it's cronfile complaining, why don't we do the `s/./_` directly there instead of touching more generic variables?

Because it's the variable is not that generic (it's only used as the internal restic repo name and for this wrapper) and because the naming of the wrapper happens inside restic-role.

In the [restore-to-controller taskfile](https://github.com/coopdevs/backups_role/blob/master/tasks/restore-to-controller.yml#L50-L56) we do it ourselves, but at [main.yml](https://github.com/coopdevs/backups_role/blob/master/tasks/main.yml#L94-L93) we have no direct control over it, only through this variable.

Also, escaping of dots (`odoo_coopdevs_org`) is preferred over just using short domain (`odoo`) because of collisions.

**Comment by raneq** [comment]
> If it's cronfile complaining, why don't we do the `s/./_` directly there instead of touching more generic variables?

Also, it's the filename of the cronfile causing the issue. I'm not sure about what you meant with "_replace_ directly there"

**Comment by enricostano** [comment]
> Also, it's the filename of the cronfile causing the issue. I'm not sure about what you meant with "replace directly there"

Would you mind to point me to the place where we create that filename? Thanks!

**Comment by raneq** [comment]
> > Also, it's the filename of the cronfile causing the issue. I'm not sure about what you meant with "replace directly there"
> 
> Would you mind to point me to the place where we create that filename? Thanks!

Again, it's not "us" who create the filename. See the linked tasks in [my comment above](https://github.com/coopdevs/backups_role/pull/25#issuecomment-504372812) and the [external role](https://github.com/paulfantom/ansible-restic/blob/master/tasks/configure.yml#L11-L19) who uses the "restic repo name" to create the "restic wrapper filename"

**Review by enricostano — APPROVED** [review]

**Pull request merged**
